---

- name: 'Manage paedML Linux using Ansible'
  hosts: [ 'ypid_service_paedml_linux' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: ypid.paedml_linux
      tags: [ 'role::paedml_linux' ]
